name: Run Integration Tests

on:
  pull_request:
    branches:
    - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
       java-version: 21
       distribution: temurin
       cache: maven

    - name: Run integration tests
      run: ./mvnw clean integration-test
